// side bar is autogenerated from the folder structure


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Autogenerate the sidebar from the folder structure
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from the docs root folder
    },
  ],
};

module.exports = sidebars;