#!/usr/bin/env node

/**
 * Script to generate CSS color variables from colors.js
 * Run this script whenever colors.js is updated to regenerate the CSS file
 */

const fs = require('fs');
const path = require('path');
const { generateThemeCSS } = require('./colorProvider');

const outputPath = path.join(__dirname, '../css/generated-colors.css');

try {
  const cssContent = `/* This file is auto-generated by generateColors.js */
/* DO NOT EDIT THIS FILE MANUALLY */
/* To update colors, edit src/theme/colors.js and run: node src/theme/generateColors.js */

${generateThemeCSS()}`;

  fs.writeFileSync(outputPath, cssContent, 'utf8');
  console.log('✅ Successfully generated color CSS at:', outputPath);
} catch (error) {
  console.error('❌ Error generating color CSS:', error);
  process.exit(1);
}